homeassistant:
  enabled: true
advanced:
  network_key:
    - 235
    - 249
    - 29
    - 225
    - 196
    - 231
    - 217
    - 132
    - 203
    - 247
    - 204
    - 4
    - 244
    - 233
    - 14
    - 27
  pan_id: 51904
  ext_pan_id:
    - 161
    - 122
    - 166
    - 176
    - 104
    - 65
    - 86
    - 62
  log_level: info
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: ui7pho3ahgh3ohgh1xohKogoh9Eiva7ePa9beachu4boonae0mahT5oor6sha3bi
frontend:
  enabled: true
  port: 8099
serial:
  port: tcp://192.168.0.216:6638
  adapter: zstack
device_options:
  legacy: false
devices:
  '0x00124b00251374d5':
    friendly_name: Living Room Light
    icon: device_icons/b72b12bc7cc9f54d583f9cd510b0954c.png
  '0x00124b002a62ed8f':
    friendly_name: 3D Printer
    icon: device_icons/b72b12bc7cc9f54d583f9cd510b0954c.png
  '0x00124b002a6394a1':
    friendly_name: 3d printer light
    icon: device_icons/b72b12bc7cc9f54d583f9cd510b0954c.png
  '0x00124b002a62eb46':
    friendly_name: Battery Chargers
    icon: device_icons/b72b12bc7cc9f54d583f9cd510b0954c.png
  '0x00124b00251372d1':
    friendly_name: Basement PC
    icon: device_icons/b72b12bc7cc9f54d583f9cd510b0954c.png
  '0x00158d000ae4734b':
    friendly_name: Dogfood Container
  '0xb0ce1814030fc26d':
    friendly_name: '0xb0ce1814030fc26d'
  '0x282c02bfffeb6d6b':
    friendly_name: Christmas Tree
version: 4
